### ISSUE TITLE
Not a valid path value error

### ISSUE THREAD

**Issue by sme229** [nf-core/scnanoseq#32]
### Description of the bug

A path to --fasta doesn't work, I get an error that path is not valid: Not a valid path value

### Command used and terminal output

```console
nextflow run -r dev nf-core/scnanoseq --input './Elena-cDNA-2/20240624_1312_1D_PAW58377_76308a2c/fastq_pass/fastq_data.csv' --outdir scnanoseq_test --fasta './Rabbit_New/fasta/genome.fa' --gtf './Rabbit_New/genes/genes.gtf' --barcode_format 10X_3v3 -profile singularity

Plus 42 more processes waiting for tasks…
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/scnanoseq] Pipeline completed with errors-
Pulling Singularity image https://depot.galaxyproject.org/singularity/ubuntu:20.04 [cache /datasets/work/hb-rabbit-gbc/work/Maria_Jenkel_ONT_Data_04-07-2024/work/singularity/depot.galaxyproject.org-singularity-ubuntu-20.04.img]
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /datasets/work/hb-rabbit-gbc/work/Maria_Jenkel_ONT_Data_04-07-2024/work/singularity -- Use the environment variable NXF_SINGULARITY_CACHEDIR to specify a different location
ERROR ~ Error executing process > 'NFCORE_SCNANOSEQ:SCNANOSEQ:PREPARE_REFERENCE_FILES:SAMTOOLS_FAIDX'

Caused by:
  Not a valid path value: './Rabbit_New/fasta/genome.fa'
```

### Relevant files

[slurm-61436891.txt](https://github.com/user-attachments/files/17036390/slurm-61436891.txt)

### System information

nextflow version 24.04.2.5914
HPC
slurm
singularity
Linux
dev

**Comment by lianov** [comment]
Hello @sme229 : could you change the path to your reference inputs (both`--fasta` and `--gtf`) to the absolute paths instead (full path). Once you change this, can you give it a re-try and let us know?

**Comment by sme229** [comment]
Hello @lianov thank you so much, that worked!

**Comment by lianov** [comment]
Great! I will close this issue. If you end up having a general question along the way, feel free to post it in our Slack group as well.

**Comment by sme229** [comment]
Thanks @lianov I've tried to join the Slack group, but get this message: It looks like there isn’t an account on nf-core tied to this email address. Please let me know if my email address can be added to the list.

**Comment by lianov** [comment]
@sme229 : you need to first join the nf-core slack group, directions can be found at: <https://nf-co.re/join#slack>
