### ISSUE TITLE
Failed to pull singularity image

### ISSUE THREAD

**Issue by sme229** [nf-core/scnanoseq#33]
### Description of the bug

I'm running the pipeline and getting this error:

ERROR ~ Error executing process > 'NFCORE_SCNANOSEQ:SCNANOSEQ:UCSC_GTFTOGENEPRED'

Caused by:
  Failed to pull singularity image
    command: singularity pull  --name depot.galaxyproject.org-singularity-ucsc-gtftogenepred-447--h954228d_0.img.pulling.1727829650369 https://depot.galaxyproject.org/singularity/ucsc-gtftogenepred:447--h954228d_0 > /dev/null
    status : 255
    hint   : Try and increase singularity.pullTimeout in the config (current is "20m")
    message:
      FATAL:   Error making http request: Head "https://depot.galaxyproject.org/singularity/ucsc-gtftogenepred:447--h954228d_0": dial tcp 128.118.250.14:443: connect: connection refused

### Command used and terminal output

```console
nextflow run -r dev nf-core/scnanoseq --input './Elena-cDNA-2/20240624_1312_1D_PAW58377_76308a2c/fastq_pass/fastq_data.csv' --outdir scnanoseq_test --fasta '/datasets/work/hb-rabbit-gbc/work/Maria_Jenkel_ONT_Data_04-07-2024/Rabbit_New/fasta/genome.fa' --gtf '/datasets/work/hb-rabbit-gbc/work/Maria_Jenkel_ONT_Data_04-07-2024/Rabbit_New/genes/genes.gtf' --barcode_format 10X_3v3 -profile singularity
```

### Relevant files

[slurm-64022331.txt](https://github.com/user-attachments/files/17219508/slurm-64022331.txt)

### System information

nextflow version 24.04.2.5914
HPC
slurm
singularity
Linux
dev

**Comment by lianov** [comment]
Hi @sme229 : 

Thanks for reporting - this is an issue that has been observed (sporadically) in other nf-core pipelines as well, so we will need to solve it on an individual basis (unlikely to be something within scnanoseq itself).

Let's start with the following steps:

1. Please ensure you set a singularity cache directory (`$NXF_SINGULARITY_CACHEDIR`). You can do so with something like `export NXF_SINGULARITY_CACHEDIR=<path_in_your_system>`, noting that the path_in_your_system should be location with sufficient storage (a bit on this is present at <https://nf-co.re/docs/usage/getting_started/introduction/#tips-and-tricks>.

2. Please run the pipeline with the `test` profile first. This will allow you to a. ensure the pipeline is running properly with a downsample input b. along the way it will download the images, and if there are continued issues we will be able to test them quicker.

You can run the test (after completing step 1 above), with the following command: 

```
nextflow run nf-core/scnanoseq -r dev  -profile test,singularity --outdir ./scnanoseq_test_out
```

Let us know what happens with the above.

**Comment by sme229** [comment]
Hi @lianov thanks so much for your help, it has now completed successfully.
